import type { TabContext } from "@tabby/types";

const CONTEXT_RULES: Record<TabContext, string[]> = {
  work: [
    "github",
    "gitlab",
    "jira",
    "notion",
    "linear",
    "figma",
    "slack",
    "trello",
    "asana",
    "confluence",
    "docs.google",
    "sheets.google",
    "drive.google",
    "meet.google",
    "zoom",
    "stackoverflow",
    "vercel",
    "netlify",
    "railway",
    "supabase",
    "claude.ai",
    "cloudinary",
    "mongodb",
    "upstash",
    "render.com",
    "heroku",
    "firebase",
    "planetscale",
    "neon.tech",
    "prisma",
    "postman",
    "insomnia",
    "adminjs",
    "cursor.sh",
    "replit",
    "notebooklm",
    "stackblitz",
    "gemini.google",
    "google developer",
    "stitch",
    "arcade",
    "tempo",
    "designtoken",
    "style-dictionary",
    "token format",
    "token glossary",
    "ai.google",
    "gemini.com",
  ],
  research: [
    "wikipedia",
    "arxiv",
    "scholar.google",
    "pubmed",
    "jstor",
    "medium",
    "dev.to",
    "hashnode",
    "substack",
    "blog",
    "docs",
    "documentation",
    "mdn",
    "w3schools",
    "freecodecamp",
    "reactbits",
    "greatfrontend",
    "frontendmentor",
    "css-tricks",
    "smashingmagazine",
    "web.dev",
    "patterns.dev",
    "mobbin",
    "fonts.google",
    "paper",
    "smard.art",
    "landing.love",
    "aiaura",
    "ai aura",
    "portfolio",
    "designtokens.org",
    "producthunt",
  ],
  entertainment: [
    "youtube",
    "netflix",
    "twitch",
    "spotify",
    "soundcloud",
    "reddit",
    "9gag",
    "imgur",
    "tiktok",
    "disney",
    "hulu",
    "primevideo",
    "crunchyroll",
    "nkiri",
  ],
  social: [
    "twitter",
    "x.com",
    "facebook",
    "instagram",
    "linkedin",
    "threads",
    "discord",
    "telegram",
    "whatsapp",
    "messenger",
    "eventbrite",
    "contra.com",
    "community",
  ],
  shopping: [
    "amazon",
    "ebay",
    "etsy",
    "shopify",
    "aliexpress",
    "walmart",
    "bestbuy",
    "target",
    "jumia",
    "konga",
    "coingecko",
    "coinmarketcap",
    "binance",
    "exchangerate",
    "fiverr",
    "upwork",
    "freelancer",
    "jiji",
    "shutterstock",
    "contra",
    "fundraiser",
  ],
  unknown: [],
};

const matchesContext = (text: string, keywords: string[]): boolean => {
  const lower = text.toLowerCase();
  return keywords.some((keyword) => lower.includes(keyword));
};

export const detectContext = (url: string, title: string): TabContext => {
  const text = `${url} ${title}`;
  for (const [context, keywords] of Object.entries(CONTEXT_RULES) as [
    TabContext,
    string[],
  ][]) {
    if (context === "unknown") continue;
    if (matchesContext(text, keywords)) return context;
  }
  return "unknown";
};
